FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
COPY index.html /var/www/html/
RUN chmod -R g+rwx /var
RUN sed -i.bak 's/listen\(.*\)80;/listen 8080;/' /etc/nginx/default.conf
EXPOSE 8080
CMD ["nginx","-g","daemon off;"]
